CREATE TABLE "KNIGHTS" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255) NOT NULL,
    "BORN" DATE NOT NULL,
    "CASTLE" VARCHAR(255) NOT NULL,
    "HERALDRY" VARCHAR(255) NOT NULL
);

CREATE TABLE "DISCIPLINES" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255) NOT NULL,
    "START_TIME" TIMESTAMP NOT NULL,
    "END_TIME" TIMESTAMP NOT NULL,
    "MAX_PARTICIPANTS" INT NOT NULL
);

CREATE TABLE "MATCHES" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "KNIGHT_ID" BIGINT NOT NULL,
    "DISCIPLINE_ID" BIGINT NOT NULL,
    "STARTING_NUMBER" INT NOT NULL,
    "POINTS" INT
);